/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.csd402.asgnt2;
import java.util.Scanner;
import java.util.Random;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        System.out.println("This program simulates a game of rock-paper-scissors.");
        while (0 == 0) {
            Scanner z = new Scanner(System.in);
            int player_choice = 0;
            int i = 0;
            while (i == 0) {
                System.out.println("Please enter your selection:\n1. Rock\n2. Paper\n3. Scissors");
                String w2 = z.nextLine();
                player_choice = Integer.parseInt(w2);
                if (player_choice > 0 && player_choice < 4) {
                    i = 1;
                } else {
                    System.out.println("That input is not acceptable. Please try again.");
                }
                }
            Random rand = new Random();
            int computer_choice = rand.nextInt(3);
            computer_choice += 1;
            String player_choice_word = "";
            switch (player_choice) {
                case 1:
                    player_choice_word = "Rock";
                    break;
                case 2:
                    player_choice_word = "Paper";
                    break;
                case 3:
                    player_choice_word = "Scissors";
                    break;
            }
            String computer_choice_word = "";
            switch (computer_choice) {
                case 1:
                    computer_choice_word = "Rock";
                    break;
                case 2:
                    computer_choice_word = "Paper";
                    break;
                case 3:
                    computer_choice_word = "Scissors";
                    break;
            }
            System.out.println("You have selected " + player_choice_word + ".");
            System.out.println("The computer has selected " + computer_choice_word + ".");
            int resolution_case = 0;
            if (player_choice == computer_choice) {
                resolution_case = 0;
            } else if (computer_choice == 1 && player_choice == 3) {
                resolution_case = 2;
            } else if ((player_choice > computer_choice) || (player_choice == 1 && computer_choice == 3)) {
                resolution_case = 1;
            } else {
                resolution_case = 2;
            }
            switch (resolution_case) {
                case 0:
                    System.out.println("It was a draw.");
                    break;
                case 1:
                    System.out.println("You won!");
                    break;
                case 2:
                    System.out.println("You lost...");
                    break;
            }
            System.out.println("\n--This program will now repeat itself.--\n");
        }
    }
}
