/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.csd402.asgnt3;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        int max_x = 46;
        int max_y = 7;
        for(int current_y = 1; current_y <= max_y; ++current_y) {
            int j = 1;
            for (; j <= max_y - current_y; ++j) {
                System.out.print("   ");
            }
            int number = 1;
            for (int k = 1; k <= current_y; ++k) {
                System.out.print(number + "  ");
                number *= 2;
            }
            number /= 4;
            for (int m = 1; m <current_y; ++m) {
                System.out.print(number + "  ");
                number /= 2;
            }
            for (int n = 0; n <= max_y - current_y; ++n) {
                System.out.print("   ");
            }
            System.out.print("@");
            System.out.println();
        }
    }
}
